name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Install ctrf-json-reporter
      run: npm install --save-dev playwright-ctrf-json-reporter
    - name: Run Playwright tests
      run: npx playwright test
      continue-on-error: true
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - name: Publish Test Summary CTRF Results
      run: npx github-actions-ctrf ctrf/ctrf-report.json
    - name: Upload Test Summary HTML Results
      uses: actions/upload-artifact@v4
      with:
        name: html-report
        path: playwright-report/index.html
